//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaptorBackground.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CornflowerBlue")]
        public global::System.Drawing.Color fctbConOutForeColour {
            get {
                return ((global::System.Drawing.Color)(this["fctbConOutForeColour"]));
            }
            set {
                this["fctbConOutForeColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transparent")]
        public global::System.Drawing.Color fctbBackgroundColour {
            get {
                return ((global::System.Drawing.Color)(this["fctbBackgroundColour"]));
            }
            set {
                this["fctbBackgroundColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color frmMainTransparencyKey {
            get {
                return ((global::System.Drawing.Color)(this["frmMainTransparencyKey"]));
            }
            set {
                this["frmMainTransparencyKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color frmMainBackColour {
            get {
                return ((global::System.Drawing.Color)(this["frmMainBackColour"]));
            }
            set {
                this["frmMainBackColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool frmMainControlBox {
            get {
                return ((bool)(this["frmMainControlBox"]));
            }
            set {
                this["frmMainControlBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transparent")]
        public global::System.Drawing.Color frmMainForeColour {
            get {
                return ((global::System.Drawing.Color)(this["frmMainForeColour"]));
            }
            set {
                this["frmMainForeColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.FormBorderStyle frmMainBorderType {
            get {
                return ((global::System.Windows.Forms.FormBorderStyle)(this["frmMainBorderType"]));
            }
            set {
                this["frmMainBorderType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int frmMainX {
            get {
                return ((int)(this["frmMainX"]));
            }
            set {
                this["frmMainX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int frmMainY {
            get {
                return ((int)(this["frmMainY"]));
            }
            set {
                this["frmMainY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("647")]
        public int frmMainCx {
            get {
                return ((int)(this["frmMainCx"]));
            }
            set {
                this["frmMainCx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("357")]
        public int frmMainCy {
            get {
                return ((int)(this["frmMainCy"]));
            }
            set {
                this["frmMainCy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmMainLocation {
            get {
                return ((global::System.Drawing.Point)(this["frmMainLocation"]));
            }
            set {
                this["frmMainLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LawnGreen")]
        public global::System.Drawing.Color lblAllowedForeColour {
            get {
                return ((global::System.Drawing.Color)(this["lblAllowedForeColour"]));
            }
            set {
                this["lblAllowedForeColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public global::System.Drawing.Color lblRestrictedForeColour {
            get {
                return ((global::System.Drawing.Color)(this["lblRestrictedForeColour"]));
            }
            set {
                this["lblRestrictedForeColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color lblCriminalForeColour {
            get {
                return ((global::System.Drawing.Color)(this["lblCriminalForeColour"]));
            }
            set {
                this["lblCriminalForeColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DimGray")]
        public global::System.Drawing.Color PanelTopBackColour {
            get {
                return ((global::System.Drawing.Color)(this["PanelTopBackColour"]));
            }
            set {
                this["PanelTopBackColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color PanelTopTextForeColour {
            get {
                return ((global::System.Drawing.Color)(this["PanelTopTextForeColour"]));
            }
            set {
                this["PanelTopTextForeColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightSteelBlue")]
        public global::System.Drawing.Color tbInputBoxActive {
            get {
                return ((global::System.Drawing.Color)(this["tbInputBoxActive"]));
            }
            set {
                this["tbInputBoxActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserUsername {
            get {
                return ((string)(this["UserUsername"]));
            }
            set {
                this["UserUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserPassword {
            get {
                return ((string)(this["UserPassword"]));
            }
            set {
                this["UserPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SessionAuthentication {
            get {
                return ((string)(this["SessionAuthentication"]));
            }
            set {
                this["SessionAuthentication"] = value;
            }
        }
    }
}
